apiVersion: v1
kind: Service
metadata:
  name: sassapp-service
  labels:
    app: sassapp
spec:
  type: LoadBalancer
  selector:
    app: sassapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
